### ISSUE TITLE
How is this different than other GWT gradle plugins

### ISSUE THREAD

**Issue by hrstoyanov** [ascendtech/gwt-gradle#1]
How is your gradle plug in better?

**Comment by mdavis95** [comment]
https://github.com/Putnami/putnami-gradle-plugin seems to be a nice plugin but I am not aware of any webpack functionality 
https://github.com/steffenschaefer/gwt-gradle-plugin is also a well known plugin.  I do not like the way project libraries are handled by this plugin

This plugin is build on four pieces:
gwt.modern
gwt.classic
gwt.lib
js.npm

GWT classic and GWT lib seem to do similar things to the putnami and steffenschaefer plugin although putnami and steffenschaefer are more full featured.

GWT modern is focused on using GWT with webpack and using GWT as a frontend only technology.  GWT lib also works with GWT modern to allow shared project libraries.  JS NPM is just for the webpack and NPM support need here.

GWT classic exist mainly because we used it internally and we wanted to be able to mix classic GWT projects using webpack and modern GWT projects using webpack in the same repository using the same shared projects (GWT Lib)
